#!/bin/bash

cat <<EOF >> webserver.py
import http.server
import socketserver
import socket

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "text/html")
        self.end_headers()

        hostname = socket.gethostname()
        # Some custom HTML code, possibly generated by another function
        html = f"Hello from {hostname}!"

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return

# Create an object of the above class
handler_object = MyHttpRequestHandler

PORT = 8080
my_server = socketserver.TCPServer(("", PORT), handler_object)

# Star the server
my_server.serve_forever()

EOF

nohup python3 webserver.py &
